### ISSUE TITLE
2.25.0 only partly fetches new items for all my feeds but then "stalls" with spinners for multiple feeds.

### ISSUE THREAD

**Issue by guigirl42** [SmartRSS/Smart-RSS#222] opened 2023-03-04 01:15 UTC
Hello & thank you very much for your brand-new update [which i confess, i'd not expected, given some of your previous notes here ;-)]. Sadly, it seems not working properly for me [i have verified the same problem in FF-Nightly, Beta, & Release]. This is a new issue; v2.23 never did this [& i never got 2.24].

Both via auto/timed update-checks, & also when i try to manually update, one or two new items appeared but then all further progress stalls, with the "spinner" animated icon just permanently "whirling" for numerous feeds in my list. All these feeds used to work with the previous version, & still work in Feedbro. 

I hope it is fixable. Thanks.

**Comment by zakius** [comment] 2023-03-04 07:48
Could you try opening `about: debugging `, This Firefox, finding SmartRSS on the list, clicking `Inspect` and observing what shows in the console when the progress stalls? Especially red entries. You can redact any addresses that appear there as these most likely won't matter for now

**Comment by gabri25ele** [comment] 2023-03-04 08:09
I confirm, I updated manually and the program froze on the fifth feed, without updating anything

![stuck](https://user-images.githubusercontent.com/33927879/222884870-674bfe44-9ad5-47b6-82a0-8667eece701c.png)

**Comment by zakius** [comment] 2023-03-04 08:46
thank you, now I known what to look for, unfortunately it may take some time as I never stumbled upon this bug

**Comment by guigirl42** [comment] 2023-03-04 09:17
> as a workaround for now you can try disabling auto removal of old entries, that should allow the process to continue

Oh wow, thanks! I made that change, manually synched, & immediately received all the "missing" new items -- no stalling now. Woohoo! 

Btw, the auto-removal has never worked for me anyway [i just left it enabled more out of hope than usefulness], & so historically i have had to periodically look at each of my many feeds then manually delete the older ones.

**Comment by gabri25ele** [comment] 2023-03-04 09:38
> as a workaround for now you can try disabling auto removal of old entries, that should allow the process to continue

but in this way do not go to accumulate too many articles? 
I remember that I had to enable it because the program had become very slow

**Comment by zakius** [comment] 2023-03-04 10:00
personally I remove things manually once I'm done with these, but at one point I had around 10k articles and it still worked relatively fine

and that's just a temporary workaround, I'll release the fix next week

> Btw, the auto-removal has never worked for me anyway

I'll try getting this fixed for the next release too, but that may require more debugging to get it done

**Comment by giiutfff** [comment] 2023-03-04 16:28
I am having similar issue. Only the first fetch works, anything after first feed fails.

> as a workaround for now you can try disabling auto removal of old entries, that should allow the process to continue

No effects for me. 

btw 2.24 already had some fetch issue (specifically it doesn't stop some of the rotate icons after fetching), but it at least fetches everything.

**Comment by zakius** [comment] 2023-03-04 17:07
There shouldn't be any real difference between 2.24 and 2.25 in that matter, but just to make sure could you try providing error logs too?

**Comment by guigirl42** [comment] 2023-03-05 00:21
Hi again @zakius .  I also have this problem; it is afaik NOT new to 2.25.0, albeit sadly it definitely still occurs in this new version. It's actually one of the main reasons that historically, each time i have tried to make your AO my default, i have to keep returning to Feedbro, for reliability.

Specifically, atm each of the following feeds, common to both AOs, work reliably in Feedbro but in SmartRSS it's either not at all, or hit & miss [ie, fetching some but not all new updates for these feeds]:

ABC Ockham’s Razor
https://www.abc.net.au/feeds/2883682/podcast.xml

OMG! Linux » Feed
https://www.omglinux.com/feed/

ABC This Week
https://www.abc.net.au/radio/programs/this-week/feed/13499150/podcast.xml

ABC What The Duck?!
https://www.abc.net.au/radionational/programs/what-the-duck/feed/13709150/podcast.xml

Jay's LearnLinuxTV
https://www.youtube.com/feeds/videos.xml?channel_id=UCxQKHvKbmSzGMvUrVtJYnUA

Guardian Oz YT
https://www.youtube.com/feeds/videos.xml?channel_id=UCoWKwd06OC0Y0XpvAa8jfdw

ABC News Daily
https://www.abc.net.au/radio/programs/abc-news-daily/feed/9443166/podcast.xml

Joe Collins
https://www.youtube.com/feeds/videos.xml?channel_id=UCTfabOKD7Yty6sDF4POBVqA

I have verified these URLs are identical in both AOs.

**Comment by guigirl42** [comment] 2023-03-05 01:46
After my preceding post, i've been trying to comply with your earlier request for the `about:debugging#/runtime/this-firefox` info. That does not work in my daily Nightly profile [the one i use all the time, & with which i created this Issue], as [amongst many other locked-down changes in my `user.js`] i disable `dom.serviceWorkers.enable`, & so i get this warning `Your browser configuration is not compatible with Service Workers. [Learn more](https://firefox-source-docs.mozilla.org/devtools-user/about_colon_debugging/index.html#service-workers-not-compatible)`.  Does correct behaviour of your AO depend on SWs being available?

Next i launched my _virgin_ Nightly profile [ie, all settings remain first-run]. Fwiw, your AO also fails to fetch _all_ the updates for _many_ of my feeds here too, apparently the same as my daily profile. I do not understand any of the results, but i saved this text file https://pastebin.com/7LJZq3zX for you, wrt the console for this profile. I made multiple attempts to fetch new feeds [meaning, the ones Feedbro gets but yours does not (yours _does_ fetch many new items, just _not all_ of them]. I selected "All Feeds" then clicked "Update all" [did not work]. I later selected some of the individual not-updating feeds, right-clicked & picked "Update" [did not work], then tried "Refetch" [weirdly this is a terrible option, coz instead of doing what it says, it actually _removes all the older_ items for each such feed!].

**Comment by giiutfff** [comment] 2023-03-05 09:54
> There shouldn't be any real difference between 2.24 and 2.25 in that matter, but just to make sure could you try providing error logs too?

Unfortunately I can't get a useful log.
![](https://user-images.githubusercontent.com/100567688/222953467-db147dfd-9cc5-4365-8d75-0c553bfdeef8.png)

btw the browser complained it needs new permissions, after the update.

> do you happen to use multiple feeds from the same service? 

Yes!

**Comment by zakius** [comment] 2023-03-05 13:30
@guigirl42 ServiceWorkers aren't required in any way unless something changed in Nightly in preparations for Mv3, but that's unlikely. Overall it seems we have 3 different issues reported in this thread, I'll start with releasing bugfixes for ones introduced in 2.24 and 2.25 and then will investigate yours. Though some mismatches may come from different handling of future dates and such, once I'm done with fixes for new ones let's move to a new thread and figure out what exactly is happening

@giiutfff in that case I know what the issue is and the fix will be ready in a day or two, I'm really sorry for all these issues

**Comment by guigirl42** [comment] 2023-03-06 00:49
![image](https://user-images.githubusercontent.com/76090786/222996420-01e96ad1-2d90-4723-96ae-8992d76f01e2.png)

**Comment by guigirl42** [comment] 2023-03-06 01:39
Oh no. This is another bug, a pretty weird one... this new feed has been misinterpreted in SmartRSS.

![image](https://user-images.githubusercontent.com/76090786/222999754-102a7eb2-9de1-4938-a7ea-99bbd655a701.png)

"What’s in the air in East Palestine, Ohio?" _is_ correct, & the actual audio file accompanying it _is_ correct... but all the accompanying descriptive text is wrong -- it actually comes from another new feed today; https://7ampodcast.com.au/episodes/asio-is-worried-youre-helping-foreign-spies

:open_mouth: :woman_shrugging:

**Comment by zakius** [comment] 2023-03-06 11:24
Patched version will be released today, due to amount of bugs introduced in 2.24 and 2.25 I'll be closing this thread and asking everyone, who reported here, to verify if their issues got fixed, and if not, to report remaining ones in new, separate issues

**Closed by zakius** 2023-03-06 11:24 UTC
