### ISSUE TITLE
Favicons Overlapping

### ISSUE THREAD

**Issue by AmmarSaleemG** [SmartRSS/Smart-RSS#198] opened 2021-12-18 18:06 UTC
Hello, this picture below depicts that favicons overlap on the headline of the article. Secondly, The favicons are not vertically positioned at centre when "Show full headline" is enabled.

![image](https://user-images.githubusercontent.com/15247707/146651321-0ba358fb-aa60-4f4a-906f-0fd930905f61.png)

**Comment by zakius** [comment] 2021-12-19 19:04
duplicate of #192

**Closed by zakius** 2021-12-19 19:04 UTC
Labels: bug
