### ISSUE TITLE
missed feed items

### ISSUE THREAD

**Issue by atomGit** [SmartRSS/Smart-RSS#194] opened 2021-10-18 11:00 UTC
not all feed items are being read for some feeds

example: `https://www.redvoicemedia.com/feed/`

when updating the feed, or re-fetching the feed, all items for the last 2 days (10-17, 10-18) are skipped

**Comment by zakius** [comment] 2021-10-18 12:38
I cannot reliably reproduce the issue, the version I am running daily is not published yet and may include a fix for this, but checking the published one it looks like it often fails to load the feed at all, but when it manages to articles are loaded properly


If you are able to could you try using the latest commit? 

running 
````
git clone git@github.com:zakius/Smart-RSS.git smartrss
cd smartrss
npm install
grunt prepare
````
will generate `dist/firefox` and `dist/chromium` directories you can load in respective browsers as temporary extensions, preferably do it in separate profile to not risk damaging your data.

**Comment by zakius** [comment] 2022-03-19 00:11
Do you have any update on this issue?

**Comment by atomGit** [comment] 2022-03-19 01:24
i do not - the problem may be with the feed for that particular website - i just refreshed that feed again and got 20 new articles, all dated for the 19th - today is the 18th and it's a US site - i'll let it up to you decide whether to close the issue, but i have nothing to add at this time

**Closed** 2022-04-21 20:04 UTC
Labels: question, feed-issue
