### ISSUE TITLE
Issue with V 2.16.2 and Firefox.

### ISSUE THREAD

**Issue by BNGI** [SmartRSS/Smart-RSS#121] opened 2020-06-18 17:10 UTC
Since V 2.16.2 every time you open the Smart-RSS window, all posts are re-downloaded and re-displayed again.

You close and re-open the reader 10 times, and each posts shows up 10 times. Also, even if posts are already marked as read, every time the reader windows is open, there is always at least one each that is marked as not-read.

**Comment by zakius** [comment] 2020-06-18 18:39
I'm looking into this, this issue surfaces because I had to modify historical IDs of items to apply one of fixes and for some reason flag I set after doing so doesn't always load from store

**Comment by zakius** [comment] 2020-06-18 18:51
version 2.16.4 I just uploaded to AMO hopefully will fix this issue, unfortunately I can't be sure as I can't reliably reproduce it, it sometimes just happens.
Unfortunately I can't automatically clean up duplicated items, I'm really sorry for the trouble

Leaving this open just in case

**Comment by BNGI** [comment] 2020-06-18 22:25
It seems to work. The icon still shows the arrow orange often (indicating new source), but when I open the reader window, there's no new message (correctly), messages are not duplicated, and they remain marked as read the way they were.

Also, settings don't seem to reset to their default on browser opening anymore.

Thank you,

**Comment by zakius** [comment] 2020-06-19 07:15
yeah, I have few ideas how to improve new sources handling, sorry about that

once again sorry about the trouble, closing this now

**Closed by zakius** 2020-06-19 07:15 UTC
Labels: bug

**Comment by BNGI** [comment] 2020-06-19 15:13
No need to be sorry. Thank you for the fix.
